---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: network-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.6.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 15m
  values:
    controller:
      replicaCount: 3
      updateStrategy:
        type: RollingUpdate # * Spins up a new pod before the old pod
        rollingUpdate:
          maxSurge: 1
      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 172.16.16.204
        externalTrafficPolicy: Local
      publishService:
        enabled: true # * If not set, it will report back the status and what IP address
      ingressClassResource:
        default: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: >-
          403,404,500,501,502,503
        enable-brotli: "true" # * Compression Algorithym
        enable-real-ip: "true"
        #forwarded-for-header: "CF-Connecting-IP"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: 0
        proxy-buffer-size: "16k"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
