apiVersion: v1
kind: Secret
metadata:
    name: shlink-secrets
    namespace: tools
stringData:
    GEOLITE_LICENSE_KEY: ENC[AES256_GCM,data:8zCSvCCPG6VD6VGwLTeKO14gr9bfqKEta/eQtcz8Y63d9LCG7elLmg==,iv:/HmMYbk4pVNP5GmK1IeMCIzVIjUk0F0WdxBR+69lNCQ=,tag:0BvhSK0Y+YCQ4By/zNptGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QUp2MWl2VDl0YUFTNGx2
            QTlYRlV6L3lLRnY3UHBTMUhRam1zdm5tTVNrCjJ6MlZJM3duTnlxRWRtaXNHWTIw
            T0ppTEhaSVNTcGJNaUZyM3FhUVhqL3cKLS0tIDVrR0dibzg0ZnNuY0I3alpEYnlz
            ekNJdTROL3Vzd09xWW5GNDdxOWM5RW8KC486z4ercDOc6ozSgJmLgiigyXqW2UpS
            1ll+hz0kwGaZK5wxVjGBuAt5HnrfVX9txhZO6i5VS3WecsRZ1h2i6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T03:28:49Z"
    mac: ENC[AES256_GCM,data:uPucqV5Y5vJ0d3dkeY7V7XIeZZk4ZQx84IEZH+oQkPsvvjeSTikt4o9/mLRbTN76AOPHyRCPiudjL7D6uvt2N1d09O/5ZuwCyt6G8AiG4PsRGgP1k3sZvpJLfaNeva4aGmi14t6s3/DZpMGH+oNOktg3DFLXrsnGR07e/afrHAs=,iv:V5mUzOGS3gFsF4MV7YGZCzzwx55oY0YrdJgX0U8Qo8A=,tag:b2NM7IrwiJ49bds9EFPCOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
