---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - overseerr/ks.yaml
  - bazarr/ks.yaml
  - recyclarr/ks.yaml
  - tautulli/ks.yaml
  - sabnzbd/ks.yaml
  - qbittorrent/ks.yaml
  - plex-auto-languages/ks.yaml
  - ytdl-sub/ks.yaml
  # - jellyfin/ks.yaml
  - plex/ks.yaml
