---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sonarr/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - overseerr/ks.yaml
  - bazarr/ks.yaml
  - recyclarr/ks.yaml
