---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-ytdl-sub
  namespace: flux-system
spec:
  dependsOn:
    - name: media-ytdl-sub-config
  path: ./kubernetes/apps/media/ytdl-sub/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-ytdl-sub-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/ytdl-sub/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
