---
buckets:
  - extras
  - main
  - versions
  - games
chocolates:
# Drivers
  - amd-ryzen-chipset
  - geforce-game-ready-driver
  - hwinfo
  - dropbox
  - obs-studio
  - discord
  - vortex
scoops:
# Drivers
  - nvcleanstall
# Games
  - sunshine
  - ryujinx
  - steam
  - epic-games-launcher
  - playnite
  - prismlauncher
# Development
  - k9s
  - git
  - neovim
  - vscode
  - hugo
  - rclone
  - openlens
  - starship
  - chezmoi
  - podman-desktop
  - bitwarden-cli
  - pwsh
  - kubectl
# Tools
  - 7zip
  - sharex
  - postman
  - powertoys
# Communication
  - whatsapp
  - zoom
  - slack
# Utilities
  - bitwarden
  - authy
  - vlc
  - obsidian
  - plex-desktop
  - prusaslicer
  - firefox
  - qbittorrent
