---
# Set the user
common_user: ubuntu

# Docker Configurations
docker_edition: 'ce'
docker_package_state: latest
docker_users: "{{ common_user }}"
docker_services: 
  - name: Docker Service
    value: docker.service
  - name: Docker Socket
    value: docker.socket

common_env: &common_env
  TZ: America/New_York
  PUID: "1000"
  PGID: "1000"

service_definitions:
  - name: wireguard
    image: lscr.io/linuxserver/wireguard:1.0.20210914
    capabilities:
      - net_admin # Allows modifications of net utils
      - sys_module # Allows privileged operations on non-root systems
    env: "{{ common_env }}"
    ports: [3001:3001]
    volumes:
      - "{{ configuration_path }}/wireguard:/config"
      - /lib/modules:/lib/modules
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    networks:
      - name: net_swag

  - name: twingate-connector
    image: twingate/connector:1.59.0
    env:
      - SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      - TWINGATE_API_ENDPOINT: /connector.stock
      - TWINGATE_NETWORK: chkpwd
      - TWINGATE_ACCESS_TOKEN: "{{ OCI_TWINGATE_ACCESS_TOKEN }}"
      - TWINGATE_REFRESH_TOKEN: "{{ OCI_TWINGATE_REFRESH_TOKEN }}"
      - TWINGATE_LOG_LEVEL: 3
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"

  - name: uptime-kuma
    image: louislam/uptime-kuma:1.23.0
    volumes:
      - "{{ configuration_path }}/uptime-kuma:/app/data" 
    network_mode: container:wireguard

  - name: swag
    image: "{{ linuxserver_image }}/swag:latest"
    ports:
      - 443:443
      - 80:80
    env:
      <<: *common_env
      URL: chkpwd.com
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: cloudflare
      EMAIL: "{{ CF_EMAIL }}"
      STAGING: "false"
      DOCKER_MODS: linuxserver/mods:swag-auto-reload
    volumes:
      - "{{ configuration_path }}/swag:/config"
    networks:
      - name: net_swag
