version: '3.1'
services:
  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: obsidian
      POSTGRES_PASSWORD: obsidian
      POSTGRES_DB: obsidiandb
      PGDATA: /data
    ports:
      - 5000:5432
    volumes:
      - ./pgdata:/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
