---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-security-external-secrets
  namespace: flux-system
spec:
  path: ./kubernetes/core/security/external-secrets-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-security-external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
  - name: core-security-external-secrets
  path: ./kubernetes/core/security/external-secrets-system/stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
