---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn-recurring-jobs
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn-recurring-jobs
      version: 5.0.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: tyzbit
        namespace: flux-system

  upgrade:
    force: true # force resource updates through a replacement strategy

  values:
    minuteStep: 5
    hourStep: 2
    createStorageClasses: true
    storageclass:
      allowVolumeExpansion: true
      reclaimPolicy: Retain

    parameters:
      replicaAutoBalance: best-effort
      dataLocality: best-effort
      numberOfReplicas: 3
      staleReplicaTimeout: 30

    groups:
      "Database":
        backup:
          - interval: 24h
            retain: 2
        filesystem-trim:
          - interval: 24h
      "Config":
        backup:
          - interval: 24h
            retain: 2
        filesystem-trim:
          - interval: 24h
      "Media":
        backup:
          - interval: 24h
            retain: 2
        filesystem-trim:
          - interval: 24h
      "Clusters":
        options:
          parameters:
            numberOfReplicas: "1"
        backup:
          - interval: 24h
            retain: 1
        filesystem-trim:
          - interval: 24h
      "Game-Servers":
        options:
          parameters:
            numberOfReplicas: "1"
        backup:
          - interval: 24h
            retain: 1
        filesystem-trim:
          - interval: 24h
      "Misc":
        options:
          parameters:
            numberOfReplicas: "1"
        filesystem-trim:
          - interval: 24h
