apiVersion: v1
kind: Secret
metadata:
    name: bws-secrets
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:Jda9dwuEjWh2VG5FYtCTaiRdG/Vi/L7iw6a6sj3d0puFliPozxr03ObHYupJpfxhg50WUsSQ94CXK/qlbQYpmUYdgT5inj/oY0qWqPksTzVRbSLkrnMP2ycJswirHw==,iv:7TcMAlzCe4fGvPAAMh+N9BW26NGeF4eLoYClg1JPWG4=,tag:g1HBJDheeJ6lwXUDzIiz8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScGM5aktWVUlpeWVkL2Jj
            dThocEdnR1U2bENybFF1QWx2cStOTkN6dm1ZCjRTWGk3bWhlKzJCOXlmdUpVajh0
            NTBsMDdPV3JNOGgwYzZkS2hDa1BCbUUKLS0tIGZqaEhrUjR4Q1ZsU1JXenp6UCt5
            eVZ2bEoxcHBQQXU5bzl5V1ExMDBUTDQKtAXI5/EBal9CAFZwG5WNGRZgo5WthoKP
            lP6z5N7eTo3d9Aogmxd/dUBKcM4xlD0zh+ruy/oqv0qzBmfbnfg6Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T14:19:19Z"
    mac: ENC[AES256_GCM,data:ZpY373TZBfHdkUzjCNbW+MxGwtC5aoSl0Uj53XL4l+Wefe+o5jc4+MPkrVA7M034M7FKgyKoMUjuRC4pt1c8CyxgGFzb9rYlM8By4mKoZHDvDjRhqtm/u/QYvuz+W74neDokvhGmetWrY5nObWy1N0zEiu6NumeNYxQk8kCNFp0=,iv:TkJdEkGN98/YNPpdvo4Q5nyochidjJYjpSLFAZEvV/M=,tag:ol2XQWAt6yHBuvPbJbN8uQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
