---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx-chart.yaml
  - longhorn-chart.yaml
  - podinfo-chart.yaml
  - metallb-chart.yaml
  - jetstack-chart.yaml
  - bitnami-chart.yaml
  - awx-chart.yaml
  - bjw-s-charts.yaml
  - actions-runner-controller.yaml
  - jameswynn-chart.yaml
