---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
  - external-secret.yml
configMapGenerator:
  - name: mediamanager-config
    files:
      - ./config.toml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: mediamanager-entrypoint
    files:
      - ./entrypoint.sh
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
generatorOptions:
  disableNameSuffixHash: true
