---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yml
  - bitwarden-secrets-manager.yml
  - cloudflare-cluster-es.yml
  - source.yml
  - generators.yml
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml=./values.yml
configurations:
  - ./kustomizeconfig.yml
