---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zipline-db
  namespace: tools
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.10.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami-chart
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    global:
      fullnameOverride: *app

    containerSecurityContext:
      runAsUser: 0

    primary:
      persistence:
        enabled: true
        existingClaim: zipline-db-pvc

      initdb:
        scripts:
          init-zipline.sql: |
            CREATE ROLE "zipline" WITH LOGIN PASSWORD '${DB_PWD_ZIPLINE}';
            CREATE DATABASE zipline WITH OWNER 'zipline' ENCODING 'UTF8' TEMPLATE template0;

      resources:
        requests:
          cpu: 15m
          memory: 226M
        limits:
          memory: 226M

  valuesFrom:
    - kind: Secret
      name: zipline-secrets
      valuesKey: POSTGRESQL_PASSWORD
      targetPath: auth.postgresPassword