---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: network-system
spec:
  ipAddressPools:
    - default-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: network-system
spec:
  addresses:
    - 172.16.16.204-172.16.16.210
