---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - miniflux/ks.yaml
  - linkding/ks.yaml
  - it-tools/ks.yaml
  - shlink/ks.yaml
  - immich/ks.yaml
  - runwhen-local/ks.yaml
  # - esxi-config-backup/ks.yaml
