---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: meshmon-config
  namespace: tools
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: meshmon-config
    template:
      engineVersion: v2
      data:
        key: "{{ .private_key | b64dec }}"
        nodeconf.yml: |
          networks:
            - directory: homies
              node_id: chkpwd
              config_type: git
              git_repo: https://github.com/rippleFCL/distmon-test.git
              discord_webhook:
                int-webhook: "{{ .webhook_url }}"
                homelads-meshmon: "{{ .homelads_webhook_url }}"
  dataFrom:
    - extract:
        key: "meshmon"
