---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autocaliweb
  namespace: &ns tools
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/autocaliweb/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # components:
  #   - ../../core/keda-operator/_components/nfs/
  postBuild:
    substitute:
      APP: *app
      CLAIM: config-autocaliweb-0
      VOLSYNC_PUID: "1000"
      VOLSYNC_PGID: "1000"
      VOLSYNC_CAPACITY: "500Mi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
    namespace: flux-system
  wait: false
  interval: 30m
