---
- name: Configure SWAG instance
  hosts: ct-01-ec2
  become: true

  tasks:

    - name: Create necessary directories
      ansible.builtin.file: # noqa risky-file-permissions
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ configuration_path }}/swag/dns-conf"
        - "{{ configuration_path }}/swag/nginx/site-confs"
        - "{{ configuration_path }}/wireguard/wg_confs/"

    - name: Create wireguard config
      ansible.builtin.copy:
        content: |
          [Interface]
          PrivateKey = {{ WIREGUARD_CLIENT_PRIVATE_KEY }}
          ListenPort = {{ WIREGUARD_PORT }}
          Address = 10.6.6.5/24
          DNS = 10.6.6.1, local.chkpwd.com

          [Peer]
          PublicKey = {{ WIREGUARD_PEER_PUBLIC_KEY }}
          AllowedIPs = 0.0.0.0/0
          Endpoint = {{ PUBLIC_IP_ADDRESS }}:{{ WIREGUARD_PORT }}
        dest: "{{ configuration_path }}/wireguard/wg_confs/wg0.conf"
        owner: "root"
        group: "root"
        mode: '600'

    - name: Template NGINX config
      ansible.builtin.template:
        src: ../../templates/nginx.conf.j2
        dest: "{{ configuration_path }}/swag/nginx/site-confs/default.conf"
        mode: '664'

    - name: Copy Cloudflare config
      ansible.builtin.copy:
        content: |
          dns_cloudflare_api_token = "{{ SWAG_CF_API_TOKEN }}"
        dest: "{{ configuration_path }}/swag/dns-conf/cloudflare.ini"
        mode: '400'

    - name: Create network(s)
      community.docker.docker_network:
        name: "{{ item.name }}"
        ipam_config:
          - subnet: "172.23.{{ item.octet }}.0/24"
            gateway: "172.23.{{ item.octet }}.1"
            iprange: "172.23.{{ item.octet }}.0/26"
      loop:
        - name: net_swag
          octet: 28
