---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rmfakecloud
spec:
  refreshInterval: 3h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rmfakecloud
    template:
      engineVersion: v2
      data:
        JWT_TOKEN: "{{ .jwt_token }}"
  dataFrom:
    - extract:
        key: "infra-media-secrets"
