---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rmfakecloud
  namespace: &ns tools
spec:
  targetNamespace: *ns
  path: ./kubernetes/apps/rmfakecloud/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../core/volsync/components/
  postBuild:
    substitute:
      APP: *app
      CLAIM: config-rmfakecloud-0
      VOLSYNC_PUID: "65534"
      VOLSYNC_PGID: "65534"
      VOLSYNC_CAPACITY: "5Gi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
    namespace: flux-system
  wait: false
  interval: 30m
