---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  values:
    controller:
      replicaCount: 3

      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1

      extraArgs:
        default-ssl-certificate: cert-manager/chkpwd-cert-production

      service:
        enabled: true
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${NGINX_LB_EXT_ADDRESS}
        type: LoadBalancer
        externalTrafficPolicy: Cluster

      publishService:
        enabled: true

      ingressClassResource:
        name: ext-ingress
        default: false
        controllerValue: k8s.io/ingress-nginx-external

      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values:
                - ext-ingress

      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        enable-brotli: "true" # * Compression Algorithym
        enable-real-ip: "true"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: 0
        proxy-buffer-size: "16k"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"

      resources:
        requests:
          cpu: 10m
          memory: 196Mi
        limits:
          memory: 221Mi
