---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: actions-runner-controller
#   namespace: flux-system
# spec:
#   path: ./kubernetes/apps/continuous-integration/actions-runner-controller/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: chkpwd-ops
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: actions-runners
#   namespace: flux-system
# spec:
#   path: ./kubernetes/apps/continuous-integration/actions-runner-controller/runners
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: chkpwd-ops
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
