---
- name: Create a login user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34313630313764323632366530383830383565636135666464393137316533653931643964653136
      3063616538643837613566613939616435643233393031340a643235386635633432623262636239
      62616539326436306339363461376235616434393438643666353836363038663033386436623036
      3733306361343338630a396266313566326662666331346137643861373830646364643734653137
      32353535616239306431333231656662333261343130383339303964373630376231303062366566
      30653563393035336266373665306134636639656231326637343532636566313063396639613265
      63396137626566316163333336643264336235316539613365656134313837646233613831616565
      34663738323235303830636364623631386236333462333462613833303231643130333762386363
      33393762646630623736383037636535353730346264653130303666393163373635
    # groups:
    #  - sudo
    # append: true # If false, the above groups are the only groups provided to the user
    state: present
  become: true

- name: Chmod the user home directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: false
  become: true


- name: Allow sudo group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true


