- name: Mount NFS share and configure files in the correct location
  hosts: valkyrie
  become: true

  tasks:
    - name: Include task to mount nfs
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/mount_nfs.yaml"

    - name: Include tasks to unarchive the files
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/unarchive_docker_files.yaml"
