---
- name: Dynamic Role Playbook
  hosts: "{{ onhosts | default('localhost') }}"
  become: "{{ elevate | default(false)}}"
  gather_facts: true
  pre_tasks:
    - name: Warn if localhost
      ansible.builtin.pause:
        prompt: "\nWARNING: The role will run against localhost. You have 2 seconds to cancel"
        seconds: 2
      when: onhosts | default('localhost') == 'localhost'

  tasks:
    - name: Module Defaults - Docker Containers
      module_defaults:
        community.docker.docker_container:
          restart_policy: always
      when: role is defined and role == 'compose'
      block:
        - name: Run the 'compose' role
          include_role:
            name: "{{ role }}"
      
    - name: Non-module defaults
      when: role is not defined or role != 'compose'
      block:
        - name: Run other roles
          include_role:
            name: "{{ role }}"
