- name: Mount NFS Share from TrueNAS on media server
  hosts: docker_hosts
  gather_facts: true
  become: true

  tasks:
    - name: Install nfs package
      ansible.builtin.apt:
        pkg: 'nfs-common'

    - name: Create the dest directory for the mount
      ansible.builtin.file:
        path: "{{ docker_confs_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Mount NFS share from TrueNAS
      ansible.posix.mount:
        src: "{{ docker_confs_nfs }}:/mnt/media/docker-confs"
        path: "{{ docker_path }}"
        opts: rw,sync,hard,nofail
        state: mounted
        fstype: nfs

    - name: Mount NFS share from TrueNAS
      ansible.posix.mount:
        src: "{{ docker_confs_nfs }}:/mnt/media"
        path: "{{ media_path }}"
        opts: rw,sync,hard,nofail
        state: mounted
        fstype: nfs
      when: ansible_hostname == "mirage"
