---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: awx-chart
  namespace: flux-system
spec:
  interval: 30m
  url: https://ansible.github.io/awx-operator/
  timeout: 3m
