---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx-operator
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: awx-operator
      version: 2.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: awx-chart
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    fullnameOverride: &app awx
    AWX:
      enabled: true
      name: *app
      spec:
        admin_user: admin
        admin_email: ${AWX_ADMIN_EMAIL}
        admin_password_secret: ${AWX_ADMIN_PASSWORD}
        ingress_type: ingress
        ingress_class_name: int-ingress
        hostname: &host "awx.${K8S_GATEWAY_DOMAIN}"
        ingress_path: /
        ingress_path_type: Prefix
        ingress_tls_secret: *host
        extra_volumes: |
          - name: ansible-cfg
            configMap:
              defaultMode: 420
              items:
                - key: ansible.cfg
                  path: ansible.cfg
              name: awx-extra-configs
        ee_extra_volume_mounts: |
          - name: ansible-cfg
            mountPath: /etc/ansible/ansible.cfg
            subPath: ansible.cfg
        web_resource_requirements:
          requests:
            cpu: 250m
            memory: 2Gi
          limits:
            memory: 4Gi
        task_resource_requirements:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            memory: 2Gi
        ee_resource_requirements:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            memory: 2Gi
        postgres_storage_class: longhorn-database
        ipv6_disabled: true
