sites:
  - url: uptime.{{ remote_domain }}
    name: wireguard
    port: 3001

remote_domain: chkpwd.com

uptime_kuma_monitors:
  # Groups
  - name: &services_group Services Ping
    type: group

  # Services
  - name: OPNsense
    type: ping
    url: 172.16.16.1
    parent: *services_group

  - name: Switch
    type: ping
    url: 172.16.16.2
    parent: *services_group

  - name: ESXi-1
    type: ping
    url: 172.16.16.3
    parent: *services_group

  - name: MGMT-SRV-01
    type: ping
    url: 172.16.16.4
    parent: *services_group

  - name: DNS-SRV-02
    type: ping
    url: 172.16.16.5
    parent: *services_group

  - name: vCenter
    type: ping
    url: 172.16.16.6
    parent: *services_group

  - name: Unifi AP
    type: ping
    url: 172.16.16.9
    parent: *services_group

  - name: Kubernetes Node 1
    type: ping
    url: 172.16.16.10
    parent: *services_group

  - name: Kubernetes Node 2
    type: ping
    url: 172.16.16.11
    parent: *services_group

  - name: Kubernetes Node 3
    type: ping
    url: 172.16.16.12
    parent: *services_group

  - name: Kube-VIP LoadBalancer
    type: ping
    url: 172.16.16.13
    parent: *services_group

  - name: NAS
    type: ping
    url: 172.16.16.15
    parent: *services_group

  - name: Home Assistant
    type: ping
    url: 172.16.16.16
    parent: *services_group

  - name: Plex Server
    type: ping
    url: 172.16.20.10
    parent: *services_group

  # Sites
  - name: WinXuu
    type: ping
    url: winxuu.chkpwd.com

  - name: Tig's Blog
    type: ping
    url: blog.tiga.tech

uptime_kuma_status_pages:
  - title: "Chkpwd's Monitoring"
    description: "Hosted Services"
    slug: default
    publicGroupList:
      - name: Hosted Services Monitoring
        weight: 1
        monitorList:
          - name: *services_group
      - name: Site Monitoring
        weight: 2
        monitorList:
          - name: WinXuu
          - name: Tig's Blog
