---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true

  tasks:
    - name: Ensure Kubernetes is running
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: started

    - name: Upgrade kube-vip
      when:
        - k3s_control_node is defined
        - k3s_control_node
      ansible.builtin.template:
        src: templates/kube-vip-static-pod.yaml.j2
        dest: "{{ k3s_server_pod_manifests_dir }}/kube-vip-static-pod.yaml"
        mode: preserve
