---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.10.5
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    worker:
      replicas: 1

    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.10.5

    ingress:
      enabled: true
      ingressClassName: ext-ingress
      annotations:
        external-dns.alpha.kubernetes.io/target: ${EXTERNAL_DOMAIN}
      hosts:
        - host: &host "authentik.${EXTERNAL_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    kubernetesIntegration: true

    authentik:
      log_level: info
      error_reporting:
        enabled: true

      email:
        from: "authentik <ocid@chkpwd.com>"
        host: smtp.gmail.com
        port: 465
        use_ssl: false

    prometheus:
      serviceMonitor:
        create: true

    envValueFrom:
      AUTHENTIK_POSTGRESQL__HOST:
        secretKeyRef:
          name: authentik-pguser-authentik
          key: host
      AUTHENTIK_POSTGRESQL__NAME:
        secretKeyRef:
          name: authentik-pguser-authentik
          key: dbname
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: authentik-pguser-authentik
          key: user
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: authentik-pguser-authentik
          key: password
      AUTHENTIK_POSTGRESQL__PORT:
        secretKeyRef:
          name: authentik-pguser-authentik
          key: port
      AUTHENTIK_EMAIL__USERNAME:
        secretKeyRef:
          name: authentik-secrets
          key: email_address
      AUTHENTIK_EMAIL__PASSWORD:
        secretKeyRef:
          name: authentik-secrets
          key: app_password
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik-secrets
          key: secret_key
      AUTHENTIK_BOOTSTRAP_PASSWORD:
        secretKeyRef:
          name: authentik-secrets
          key: bootstrap_password
      AUTHENTIK_BOOTSTRAP_TOKEN:
        secretKeyRef:
          name: authentik-secrets
          key: bootstrap_token
      AUTHENTIK_BOOTSTRAP_EMAIL:
        secretKeyRef:
          name: authentik-secrets
          key: bootstrap_email

    postgresql:
      enabled: false

    redis:
      enabled: true

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    resources:
      server:
        requests:
          cpu: 19m
          memory: 562Mi
        limits:
          memory: 587Mi
      worker:
        requests:
          cpu: 11m
          memory: 604Mi
        limits:
          memory: 629Mi

