apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:WnVTL0ZXTxrTszVo/YMey6GWTGAPhU/wlhE=,iv:oxYcJJxKzcgaqQ/2SsytyDW7NXU99UyBwaHvYjlFOS4=,tag:Ps3PbgFhPZj9L2ips7GLFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QnNsdnRDZG80aWRiYkNo
            ZjdGdXM1Q2Q0OUZGdkNpZW5LY3lQNGlFSlJZClFNMis4cWQxLzkyVGsyd0IwNmds
            V3R4d3k0WVZ4THk3UjF0dW9OVzBKYncKLS0tIEhsUlVieGF0bDJPeWVvVTVpeFhN
            RkNTSmsySVJTVFFpeVF3cmFGOGs3SG8KblcEDHpV8cG8oxAASMPBpMo/7czyXvfO
            RqJWI6cX7emN25w42Cw3WLdS+Ri6pM3exUpROCeVMlmXL9vAcfp+mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T02:35:18Z"
    mac: ENC[AES256_GCM,data:mr2dsfqoOAgJS80V4QIogbN4YPwl2umtZ/LBKCW1QYGdShuVF9hOfD0gMEoM8H0Lj0y3eJWmSVRUao5pprS+KH0uREEt5hm7tpPrSqoF0yb0xtVf8pBrO4+ArOo04cOmGIcbXoK84hYnYh/eRoeV46H+3+hPZgl9cOWfW6HHt90=,iv:2zogL0SCPPVCjoWpPPkaLlaPGAqPX0tEWlcrQCCWskc=,tag:wQxGKDX6oCn91hAtlrjPog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
