---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: networking
spec:
  type: ExternalName
  externalName: mgmt-srv-01.${LOCAL_DOMAIN}
  ports:
    - name: http
      port: &port 3000
      protocol: TCP
      targetPort: *port
