apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: security
stringData:
    secret_key: ENC[AES256_GCM,data:LJWU1wWV8vmwM8ZGybUTs9F9IDClXSgBjJ8//nSJB7p4QEVUA61s35+o4b1gNlGcRns=,iv:Pu2YDrieNpN0ihR5rUpjVRqV74ly9UbOhiYgnd3V5AI=,tag:uId+hSyQqHLf+h9wK/dCEA==,type:str]
    email_address: ENC[AES256_GCM,data:wDt66NcTz+usITFUCOkIUvMROuYb,iv:OYVz3yYqMuxkJn86M0zXkhaKP6suYCIy2QfJ/g2hzWE=,tag:95RimAVWRgpYmTqbTi2jJQ==,type:str]
    app_password: ENC[AES256_GCM,data:TAUuMjCnqN6SwGMSrdsmrw==,iv:XxQA1tDKBJ9oh4tKbMGv7/LWPqQqkXgEQa/OD12oXKs=,tag:pSfl6WhVh3HAJ8LptbVvLA==,type:str]
    redis_password: ENC[AES256_GCM,data:whwM8tKtsyjvXNuUFAligLGQnxhwmU299zl60GZoO+R7AYx+2fTNrz8M5d1fUIRL,iv:I90L2UN6kKerowP8R8TPylw1U+G/jpisAaXkYo+4f30=,tag:rvFiYjCv1ZdLTMiVshz9iQ==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:jD1y6ia2JYUQaqJoS59qr0vmsU5XqnA1XabCzA==,iv:b5GVETy+QhoLpoR9m3usznu8zhWEsKKNFteza75vjmM=,tag:uI+gKh3tKdFWh1Qt/tkKXA==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:CgGFhLGh70aUdPICaGPCnZZyGmvCvsJDCExAwmUdd8BpXDyZrk3LbYz1mZfqWNYiK5FnZkh7GAuxoAexMHnW4g==,iv:k69h9jxMAm1H93fbWVcoHKIe9ObuTNUAhOx5Bp0uKL4=,tag:iMJRk7ABqXtECPn7Gmpf8A==,type:str]
    bootstrap_email: ENC[AES256_GCM,data:8u6tBgx7swoSTP7Xx771QXG+p+Y=,iv:xjVwYNGF5uDTMO6DSVwTUKO7tpsObMN+ApxuaIEEMdk=,tag:Gbq6fFJ5KGl6FoT2OK33/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUDJ3bzVGRlFJcjI5bmNi
            Wll0eFBsV3dTMjJWZkkzS0lleTk1bkRpMGg4CmJqUkIralBFNC9GRWZEQ1dnZUxl
            QnpWREZyeDNPM3lIbWhyQy9lUUVHOVEKLS0tIEZuNzJLTTFYelVrbkhkVkJXVXlP
            NUxGVGdCN1pjM1N6d1FQaFR4OG1MMkkKVDEfyk7ZdWeM25d+dPPs1feZ7Ywa5QwV
            5g+sbnz/2VsxXojIIrMp5u2wOp2rMu/1/+q9Dd6dGMn9U5CjNgbGXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T00:35:46Z"
    mac: ENC[AES256_GCM,data:3Bh/bMk8O23hyPoAH2xb1PwKJt1NH7QYG0rQ1y6P/UQN65PVDylq6RJUqSVLIt+n7Lz/9no/P3iK7dN+wGB1XhAYuLJbATvXheGyGTTSCqwIlr9HiKO82XwhQkfplhc2dd0EG20Eta5Dqs1R7APy4IOlH5pf44Nq7M8+rkhZM7U=,iv:lrxKle8QGxUIlkpbCI+2HOquGD+AYPITMebpi/bFPLg=,tag:sy5BQfwp8iA9HNPkugPwPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
