apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namePrefix: prod-

patches:
  - patch: |
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 1024M
    target:
      kind: VirtualMachine
