---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources: []
configMapGenerator:
  - name: recyclarr-cm
    files:
      - recyclarr.yml=./config/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
