---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/flux-kustomization.yml
  - cilium/flux-kustomization.yml
  - coredns/flux-kustomization.yml
  - crunchydata-pgo/flux-kustomization.yml
  - dragonfly-operator/flux-kustomization.yml
  - external-dns/flux-kustomization.yml
  - external-secrets/flux-kustomization.yml
  - flux-instance/flux-kustomization.yml
  - flux-operator/flux-kustomization.yml
  - fstrim/flux-kustomization.yml
  - gateway-api/flux-kustomization.yml
  - intel-device-plugin-operator/flux-kustomization.yml
  - kromgo/flux-kustomization.yml
  - metrics-server/flux-kustomization.yml
  - multus/flux-kustomization.yml
  - node-problem-detector/flux-kustomization.yml
  - prometheus/flux-kustomization.yml
  - reloader/flux-kustomization.yml
  - rook-ceph/flux-kustomization.yml
  - snapshot-controller/flux-kustomization.yml
  - tofu-controller/flux-kustomization.yml
  - volsync/flux-kustomization.yml
  - spegel/flux-kustomization.yml
  - grafana-operator/flux-kustomization.yml
  - keda-operator/flux-kustomization.yml
  - blackbox-exporter/flux-kustomization.yml
  - proxies/flux-kustomization.yml
