---
timezone: 'America/New_York'

ntp_timezone: '{{ timezone }}'

locale: 'en_US.UTF-8'

keyboard_layout: 'us'

dotfiles_repo: 'https://github.com/chkpwd/dotfiles'

ansible_user: hyoga

zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git

zsh_gists:
  - name: settings.zsh
    id: c078ab9da9cf8465dee808cd9058c760
  - name: path.zsh
    id: b4562691407d16aa2319b07b1ea7b36b
  - name: functions.zsh
    id: b1d162fe0171f65d27c95d2ee56a5b15
  - name: dir.zsh
    id: 5181fb70d0a43559878a34eea76214c1
  - name: aliases.zsh
    id: bbd1f0cb096146ce6736c44059c59249
