---
k3s_release_version: "v1.28.2+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_debug: false
k3s_etcd_datastore: true

kube_vip_address: 172.16.16.13
kube_vip_interface: "ens192"
kube_vip_namespace: "kube-system"

k3s_server_manifests_urls:
  # Kube-vip RBAC
  - url: https://raw.githubusercontent.com/kube-vip/kube-vip/main/docs/manifests/rbac.yaml
    filename: custom-kube-vip-rbac.yaml
k3s_server_pod_manifests_templates:
  - kube-vip-static-pod.yaml.j2

k3s_registration_address: "{{ kube_vip_address }}"

common_user: 'hyoga'
mount_dir: /mnt/data/longhorn
