---
k3s_control_node: true

k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    - "{{ kube_vip_address }}" # Floating LoadBalancer IP for Control Plane API
    - k3s-vip.local.chkpwd.com
  docker: false
  flannel-backend: "vxlan" # quote
  disable:
    - metrics-server
    - servicelb
    - traefik
    - local-storage
  write-kubeconfig-mode: "0644"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-controller-manager with kube-prometheus-stack
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"          # Required to monitor kube-scheduler with kube-prometheus-stack
  etcd-expose-metrics: true           # Required to monitor etcd with kube-prometheus-stack
  kube-apiserver-arg:
    - "anonymous-auth=true"           # Required for HAProxy health-checks
