apiVersion: v1
kind: Secret
metadata:
    name: twingate-connector
    namespace: networking
stringData:
    TWINGATE_ACCESS_TOKEN: ENC[AES256_GCM,data:oOVb2hy5m+oRXlb+jUAd88oS74VxfUYPbaFdH+A6kCSAotn6dlID3JTdlmWFlTHqZ0Z0vfKzwrcTkNA3lQruyVCTHbv5BDFknEu/tUt4FU9sw43PvClpNHu9qfDAdAU9fAUvynFGFH5vf+HMCR86fsOWsBNEgzPGbbNZdwK3t3CVgImiEO8sykyNCxudS+UjnOcexZvncdW8uKHxbkjZBE8iNxkk9byqogEqzZhv0TKG659jadZv0APPIlMviUCpQdEFvVJwI8plmVEmDpUO0TckXkoYn1xO3HPMrNptgIm4tsYIYoije+F8BrWP4gzH2CNxvE5qTclVy7pmBdoJgo41uowNfoMBlI0UhK0sPXhJHy57yJ91iIX9msh9yNsmKlsynkTteWq1oNkl3DoadWCul1Q9RQmVA9PwaHwWB+NocrZ4tDOF11vpBoDs6CHEqZzt+Bik6qT80n2cetqmOLzodoZGXtdN/tKkB2PS+ghGcoNImoBGOr8KD6d799cGbHE+kn1wjlevOttUxaIzR2hysPKU9uvnXXH9zODgn8u96Ms0SniGUtZ12QFk/vBKrwr95D+0gLIgBlBwp6Zmleq7xXYfJQW/XwwNt2OxIMWnC8UaqQbshP3b,iv:56XtI1MgQYfQBQFP6dlXI0ruxs6A3m6RKcQswnL8800=,tag:w9akRXC4Z0RNrjMcsFYUzQ==,type:str]
    TWINGATE_REFRESH_TOKEN: ENC[AES256_GCM,data:CEOZQ5noJHg74r/pFlQAY8F7Ay9sLN8khf81e3XBLvbWxRJUtDRDmhIotSXwhExXyphWGmJSeFMPCH/Ncd9vsoBB/Noe7SG5JuAbJivRaZ6ISbRe62cvOY0wcUnUKMlZfCXrB/BXdD0uuaLuEZKJCe9EVK32Mn7T7p9yv78ecCVg1HwVEbE=,iv:goY69npee/2AhleGw/OQOU4XSipA97GXmbqjTYtNuhI=,tag:+ZYyR5rmIFySco1IkV8reA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UGdUZWcvcU5LYS84amtm
            ME1yaHhpbUpmaXJXUjBLWEc3NStZU3MvV0J3CmxFSU54Q1hTMWJrMWUzTGdlL2w0
            ZUdwNE80S3E4ZjNacWNaazBmOU5lUUUKLS0tIEJuaGVIL09qNVp5MDB2aExPNXJl
            RXVITUtaSE9jTzlKU0N2TFI0VzFYQVkKzkQmaF6Xr02yUg7X1jhSFa+IH0+fwSiY
            RdOg1VDZvRts21GMU2Fv8t72CSopFAt2cvw89CxVS93Ysfl4b0Fg+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-31T03:00:31Z"
    mac: ENC[AES256_GCM,data:tBaH7ZFZSUpaPCp7/Gde87zt1B0F1pQaDupx45nyP4T2lxxRbLG2fT8zzxwMZ5i1Cbwy2+rHFO6YUNm7OvvfzZirU6SqmNHmlA00DX0R1BV5hZuOwIlnwA/fY2KJNDe6KMhTJrWnDqg1VMdJkAuEWc4sl0NUgiHWA60GApa/FZo=,iv:DUrPw6jnLlomjhEGNTCH+6DqihPaAL9+xsQmD1Nukao=,tag:G1MnT19A0Rr+YxM/fzHkGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
