---
# ansible-galaxy install -r requirements.yaml && \
# ansible-galaxy collection install -r requirements.yaml

collections:
  - name: community.docker
    version: 3.7.0
  - name: community.general
    version: 8.3.0
  - name: community.sops
    version: 1.6.7
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 3.1.0
  - name: kubernetes.core
    version: 3.0.0
  - name: community.windows
    version: 2.1.0
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: lucasheld.uptime_kuma
    version: 1.2.0
  - name: awx.awx
    version: 23.7.0

roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.4
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: arillso.logrotate
  - name: robertdebock.kubectl
  - name: stefangweichinger.ansible_rclone
