---
collections:
  - name: community.docker
    version: 5.0.5
  - name: community.general
    version: 12.2.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: community.windows
    version: 3.1.0
  - name: chocolatey.chocolatey
    version: 1.5.3
  - name: ripplefcl.bwscache
    version: 1.3.0
roles:
  - name: geerlingguy.docker
  - name: arillso.logrotate
  - name: stefangweichinger.ansible_rclone
