---
# ansible-galaxy install -r requirements.yaml && \
# ansible-galaxy collection install -r requirements.yaml

collections:
  - name: community.docker
    version: 3.4.8
  - name: community.general
    version: 7.4.0
  - name: community.sops
    version: 1.6.7
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.11.0
  - name: kubernetes.core
    version: 2.4.0
  - name: community.windows
    version: 2.0.0
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: lucasheld.uptime_kuma
    version: 1.2.0
  - name: awx.awx
    version: 23.4.0

roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  - name: geerlingguy.docker
  - name: gantsign.oh-my-zsh
  - name: arillso.logrotate
  - name: robertdebock.kubectl
  - name: stefangweichinger.ansible_rclone
