apiVersion: v1
kind: Secret
metadata:
    name: linkding-secrets
    namespace: tools
stringData:
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:scxF0Gt0PcABjHzauuFyY4KwLaTHHn8M/hQ=,iv:j8q0XHqoccxLai4ZkKc6ai8FwG0JObeFHorpHJb8FzI=,tag:B/3xrknCahzxb+lOT5hBFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1svjsaslsjmma973szm9x2slcqduz9swzyqtfszg64tsrrs95qsrspynuyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWEZNL1ZnbE5pQlJVTGVM
            OUxOamh4ejRUc2kvaWttRzRJK1FhNnpXQ1M4CjNYS0pTdldMOGRwZmJUT3p2TXY1
            dXF4RmsxV2FFb3lGNHU2UE9kQ2Vpa2MKLS0tIEU2V2FHeHFPTzI4OWNPakttbnJG
            UktFcWVNWXVOcmZ6L28vcGtDYTZ1YzQKX/MEbDfJ4r+DHa+OutGiBLX2aM8AXNqt
            vKPEXRVBeHhmaOzJyx2rWD22u3mcX4M0VpVFuDiQzP6RxblPDZqncA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-06T12:58:54Z"
    mac: ENC[AES256_GCM,data:gBPGYsgHeAIjzjC47xXaF0aH6VzpOg9lcT9Tj2krjL6tkdnkLkvagnlyNuTrnBkqEXoi7+eTv/T2q4sfSJJZvcop+L3V5gfjLqRvIEMqb5TTfhoMYOpHtazUYOGF8z8p/F+wRin+RMTm4u1o9+NdVD1iS0+Wm/l0ci9VwCmZP4M=,iv:teCazIrkxVRnESq0eu/iFI0BNtvg4oNWSdwR2bzbCc8=,tag:GdAEMNL3NKlYCcA5CJL9OQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
