---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik/flux-kustomization.yml
  - bazarr/flux-kustomization.yml
  - diff2rss/flux-kustomization.yml
  - flaresolverr/flux-kustomization.yml
  - seerr/flux-kustomization.yml
  - maintainerr/flux-kustomization.yml
  - miniflux/flux-kustomization.yml
  - paperless-ngx/flux-kustomization.yml
  - plex/flux-kustomization.yml
  - plex-auto-languages/flux-kustomization.yml
  - prowlarr/flux-kustomization.yml
  - qbittorrent/flux-kustomization.yml
  - radarr/flux-kustomization.yml
  - recyclarr/flux-kustomization.yml
  - sabnzbd/flux-kustomization.yml
  - sonarr/flux-kustomization.yml
  - tautulli/flux-kustomization.yml
  - your-spotify/flux-kustomization.yml
  - karakeep/flux-kustomization.yml
  - teslamate/flux-kustomization.yml
  - teslamateapi/flux-kustomization.yml
  - meshmon/flux-kustomization.yml
  - shelfmark/flux-kustomization.yml
  - booklore/flux-kustomization.yml
  - mediamanager/flux-kustomization.yml
