---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - paperless-gpt/flux-kustomization.yml # mkdir for db requires root
  # - semaphore/flux-kustomization.yml
  - authentik/flux-kustomization.yml
  - bazarr/flux-kustomization.yml
  - diff2rss/flux-kustomization.yml
  - flaresolverr/flux-kustomization.yml
  - immich/flux-kustomization.yml
  - jellyseerr/flux-kustomization.yml
  - maintainerr/flux-kustomization.yml
  - miniflux/flux-kustomization.yml
  - paperless-ngx/flux-kustomization.yml
  - plex/flux-kustomization.yml
  - plex-auto-languages/flux-kustomization.yml
  - prowlarr/flux-kustomization.yml
  - qbittorrent/flux-kustomization.yml
  - radarr/flux-kustomization.yml
  - recyclarr/flux-kustomization.yml
  - sabnzbd/flux-kustomization.yml
  - sonarr/flux-kustomization.yml
  - tautulli/flux-kustomization.yml
  - unifi-controller/flux-kustomization.yml
  - winxuu/flux-kustomization.yml
  - your-spotify/flux-kustomization.yml
  - karakeep/flux-kustomization.yml
  - teslamate/flux-kustomization.yml
  - teslamateapi/flux-kustomization.yml
  - calibre-web/flux-kustomization.yml
  - calibre-web-automated-book-downloader/flux-kustomization.yml
  - jellyfin/flux-kustomization.yml
  - watchstate/flux-kustomization.yml
  - meshmon/flux-kustomization.yml
  - glance/flux-kustomization.yml
