---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ark-cluster
  namespace: flux-system
spec:
  interval: 30m
  url: https://sickhub.github.io/ark-server-charts
  timeout: 3m
