---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx-chart.yaml
  - longhorn-chart.yaml
  - podinfo-chart.yaml
  - metallb-chart.yaml
  - jetstack-chart.yaml
  - bitnami-chart.yaml
  - bjw-s-chart.yaml
  - actions-runner-controller-chart.yaml
  - jameswynn-chart.yaml
  - metrics-server.yaml
  - prometheus-community-chart.yaml
  - stakater-chart.yaml
  - tyzbit-chart.yaml
  - authentik-chart.yaml
  - cloudnative-pg-chart.yaml
  - external-dns-chart.yaml
  - loft-sh-chart.yaml
  - fairwinds-chart.yaml
  - jitsi-chart.yaml
  - immich-chart.yaml
  - twingate-chart.yaml
  - botkube-chart.yaml
  - k8s-gateway-chart.yaml
  - ark-cluster-chart.yaml
  - deliveryhero-chart.yaml
  - runwhen-local-chart.yaml
  - intel-chart.yaml
  - nfd-chart.yaml
  - awx-chart.yaml
  - angelnu-chart.yaml
  - backube-chart.yaml
