---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: tyzbit
  namespace: flux-system
spec:
  interval: 30m
  url: https://tyzbit.github.io/helm-charts/
  timeout: 3m
  