---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-multus
  namespace: flux-system
spec:
  path: ./kubernetes/core/networking/multus-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-multus-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-multus
  path: ./kubernetes/core/networking/multus-system/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
