---
- name: Bootstrap Process
  ansible.builtin.include_tasks: bootstrap.yaml

- name: Set locale and timezone
  community.windows.win_timezone:
    timezone: Eastern Standard Time

- name: Change Hostname
  ansible.windows.win_hostname:
    name: chk-dev-win11
  register: hostname

- name: Install dependencies
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ chocolates }}"
  loop_control:
    label: "Chocolate: {{ item }}"

- name: Scoops - Install dependencies
  community.windows.win_scoop:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ scoops }}"
  loop_control:
    label: "Scoop: {{ item }}"

- name: Install PowerShell Core
  chocolatey.chocolatey.win_chocolatey:
    name: powershell-core
    state: present

- name: Registry Edits
  ansible.builtin.include_tasks: registry.yaml

- name: Define Taskbar Layout
  ansible.windows.win_powershell:
    script: |
      Import-StartLayout -LayoutPath "TaskbarLayout.xml" -MountPath "{{ ansible_facts.env.TEMP }}\templates\TaskbarLayout.xml"

- name: Install Windows Features
  ansible.windows.win_optional_feature:
    name: 
      - Microsoft-Windows-Subsystem-Linux
      - ServicesForNFS-ClientOnly
      - ClientForNFS-Infrastructure
    state: present
  notify: Reboot if feature requires it

- name: Change power plan to Balanced
  community.windows.win_power_plan:
    name: balanced

- name: Ensure RDP rights are given to {{ ansible_user }}
  ansible.builtin.include_tasks: users.yaml

- name: Update the system
  ansible.builtin.include_tasks: system.yaml
