---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-twingate-connector
  namespace: flux-system
spec:
  dependsOn:
    - name: networking-twingate-connector-config
  path: ./kubernetes/apps/networking/twingate-connector/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-twingate-connector-config
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/twingate-connector/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: chkpwd-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
