---
- name: Install nfs package
  ansible.builtin.apt:
    pkg: 'nfs-common'

- name: Create the dest directory for the mount
  ansible.builtin.file:
    path: "{{ media_path }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_user }}"
    mode: '0755'

- name: Mount NFS share from TrueNAS
  ansible.posix.mount:
    src: "nas-srv-01:/volume1/vault-01/{{ item }}"
    path: "{{ media_path }}"
    opts: rw,sync,hard,nofail
    state: mounted
    fstype: nfs
  loop: '{{ media_nfs_shares }}'
  loop_control:
    - label: "Mounting: {{ item }}"

- name: Configure Pigz Backup for Plex
  ansible.builtin.include_tasks: setup_backup.yaml
