- name: Install pigz
  ansible.builtin.apt:
    name: pigz
    state: present

- name: Template Plex script
  ansible.builtin.template:
    src: templates/plex_script.py.j2
    dest: ~/plex_script.py
    owner: root
    group: root
    mode: 0644
  register: script

- name: Install backup schedule
  ansible.builtin.cron:
    name: pms-backup
    cron_file: pms_backup
    user: "root"
    job: "python3 {{ script.dest }}"
    weekday: 1
    hour: 3
    minute: 0
    state: present
